CC0=cc0
FLAGS=-x

TESTS=sortedlist-test.c0
LIB=listlib.c0

all: 1 2 3 4 5

1:
	$(CC0) $(FLAGS) $(LIB) sortedlist-bad1.c0 $(TESTS)

2:
	$(CC0) $(FLAGS) $(LIB) sortedlist-bad2.c0 $(TESTS)

3:
	$(CC0) $(FLAGS) $(LIB) sortedlist-bad3.c0 $(TESTS)

4:
	$(CC0) $(FLAGS) $(LIB) sortedlist-bad4.c0 $(TESTS)

5:
	$(CC0) $(FLAGS) $(LIB) sortedlist-bad5.c0 $(TESTS)
